/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { vCOLEND__factory } from './vCOLEND__factory';
export { COLEND__factory } from './COLEND__factory';
export { COLENDGovernor__factory } from './COLENDGovernor__factory';
export { Multicall__factory } from './Multicall__factory';
