/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { vCOLEND } from './vCOLEND';
export type { COLEND } from './COLEND';
export type { ColendGovernor } from './ColendGovernor';
export type { Multicall } from './Multicall';
export * as factories from './factories';
export { vCOLEND__factory } from './factories/vCOLEND__factory';
export { Multicall__factory } from './factories/Multicall__factory';
export { COLEND__factory } from './factories/COLEND__factory';
export { COLENDGovernor__factory } from './factories/COLENDGovernor__factory';
